version: '3.7'

# This Guideline will show you how to config env
# https://medium.com/better-programming/using-variables-in-docker-compose-265a604c2006

services:
  app:
    image: app-graphql:latest
    build:
      context: .
      # Just build image `builder`. For detail, please see file `./Dockerfile`
      target: builder
    container_name: app-graphql
    platform: linux/amd64
    env_file: .env
    environment:
      APP_PORT: $APP_PORT
      NODE_ENV: $NODE_ENV
      RDS_USERNAME: $RDS_USERNAME
      RDS_PASSWORD: $RDS_PASSWORD
      RDS_DATABASE: $RDS_DATABASE
      RDS_HOST: $RDS_HOST
    ports:
      - 3000:$APP_PORT
    volumes:
      # Share directory `src` to container. This help you can auto reload server if any file in
      # directory change.
      - ./src:/builder/app/src/
      # Create volume to cache directory module. This useful for help build image fast more.
      - dev_dep:/builder/app/node_modules
      - yarn_cache:/usr/local/share/.cache/yarn
      - prod_dep:/prod_dep/node_modules
    # Start source with nodemon. For detail, read file package.json.
    command: yarn run start:dev
    networks:
      - nw_template_graphql
    depends_on:
      - db
      - redis

  db:
    image: mysql:8.0
    container_name: db-graphql
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: admin@123
      MYSQL_DATABASE: $RDS_DATABASE
      MYSQL_USER: $RDS_USERNAME
      MYSQL_PASSWORD: $RDS_PASSWORD
    ports:
      - 3306:3306
    networks:
      - nw_template_graphql
    volumes:
      - ./docker/mysql:/var/lib/mysql

  redis:
    container_name: redis-graphql
    image: redis
    ports:
      - 6379:6379
    networks:
      - nw_template_graphql
networks:
  nw_template_graphql:
    driver: bridge

volumes:
  yarn_cache:
  dev_dep:
  prod_dep:
