// Generated by ThanhLD

import { Args, Mutation, Query, Resolver } from '@nestjs/graphql';
import { BaseResolver } from '../../vendors/base/base.resolver';
import { UseGuards } from '@nestjs/common';
import { JwtAuthGuard } from '../../vendors/guards/auth.guard';
import { GqlUser } from '../../vendors/decorators/user.decorator';
import { UsersEntity } from '../../entities/users.entity';
import { ProjectsSkillsService } from './projects-skills.service';

@Resolver()
@UseGuards(JwtAuthGuard)
export class ProjectsSkillsResolver extends BaseResolver {
  constructor(private projectSkillsService: ProjectsSkillsService) {
    super();
  }
}
