// Generated by trungbb@vitalify.asia

import { DataSource } from 'typeorm';
import { Injectable } from '@nestjs/common';
import { BaseRepository } from '../vendors/base/base.repository';
// Do not delete this comment
// Append importEntity in this place
import { ProjectsSkillsEntity } from '../entities/projects_skills.entity';

@Injectable()
export class ProjectsSkillsRepository extends BaseRepository<ProjectsSkillsEntity> {
  constructor(private dataSource: DataSource) {
    super(ProjectsSkillsEntity, dataSource.createEntityManager());
  }
}
