// Generated by trungbb@vitalify.asia

import { DataSource } from 'typeorm';
import { Injectable } from '@nestjs/common';
import { BaseRepository } from '../vendors/base/base.repository';
// Do not delete this comment
// Append importEntity in this place
import { ProjectsEntity } from '../entities/projects.entity';

@Injectable()
export class ProjectsRepository extends BaseRepository<ProjectsEntity> {
  constructor(private dataSource: DataSource) {
    super(ProjectsEntity, dataSource.createEntityManager());
  }
}
