// Generated by thanhld@vitalify.asia

import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';
import { UsersDevicesEntity } from '../../entities/users_devices.entity';
import { UsersDevicesResolver } from './users_devices.resolver';
import { UsersDevicesService } from './users_devices.service';
import { UsersRepository } from '../../repositories/users.repository';
// Do not delete this comment
// Append importPackages in this place
// Start latest generated importPackages
import { UsersDevicesRepository } from '../../repositories/users_devices.repository';
import { DevicesRepository } from '../../repositories/devices.repository';
import { DevicesEntity } from '../../entities/devices.entity';

// End latest generated importPackages

@Module({
  imports: [TypeOrmModule.forFeature([UsersDevicesEntity, DevicesEntity])],
  providers: [
    UsersDevicesService,
    UsersDevicesResolver,
    UsersRepository,
    // Do not delete this comment
    // Append packageNames in this place
    // Start latest generated packageNames
    UsersDevicesRepository,
    DevicesRepository,
    // End latest generated packageNames
  ],
  exports: [UsersDevicesService],
})
export class UsersDevicesModule {}
