// Generated by ThanhLD

import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';
import { ProjectsEntity } from '../../entities/projects.entity';
import { ProjectsRepository } from '../../repositories/projects.repository';
import { ProjectsResolver } from './projects.resolver';
import { ProjectsService } from './projects.service';
import { UsersService } from '../users/users.service';
import { UsersRepository } from '../../repositories/users.repository';
import { ProjectsSkillsRepository } from '../../repositories/projects-skills.repository';
import { SkillsRepository } from '../../repositories/skills.repository';

@Module({
  imports: [TypeOrmModule.forFeature([ProjectsEntity])],
  providers: [
    ProjectsRepository,
    ProjectsService,
    ProjectsResolver,
    UsersService,
    UsersRepository,
    ProjectsSkillsRepository,
    SkillsRepository,
  ],
  exports: [ProjectsService],
})
export class ProjectsModule {}
