// Generated by trungbb@vitalify.asia

import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';
import { ProjectsEntity } from '../../entities/projects.entity';
import { ProjectsResolver } from './projects.resolver';
import { ProjectsService } from './projects.service';
import { UsersRepository } from '../../repositories/users.repository';
// Do not delete this comment
// Append importPackages in this place
// Start latest generated importPackages
import { ProjectsRepository } from '../../repositories/projects.repository';
import { ProjectsSkillsRepository } from '../../repositories/projects_skills.repository';
import { SkillsRepository } from '../../repositories/skills.repository';

// End latest generated importPackages

@Module({
  imports: [TypeOrmModule.forFeature([ProjectsEntity])],
  providers: [
    ProjectsService,
    ProjectsResolver,
    UsersRepository,
    // Do not delete this comment
    // Append packageNames in this place
    // Start latest generated packageNames
    ProjectsRepository,
    ProjectsSkillsRepository,
    SkillsRepository,
    // End latest generated packageNames
  ],
  exports: [ProjectsService],
})
export class ProjectsModule {}
