// Generated by ThanhLD

import { Args, Mutation, Query, Resolver } from '@nestjs/graphql';
import { BaseResolver } from '../../vendors/base/base.resolver';
import { UseGuards } from '@nestjs/common';
import { JwtAuthGuard } from '../../vendors/guards/auth.guard';
import { GqlUser } from '../../vendors/decorators/user.decorator';
import { UsersEntity } from '../../entities/users.entity';
import { ProjectsService } from './projects.service';

@Resolver()
@UseGuards(JwtAuthGuard)
export class ProjectsResolver extends BaseResolver {
  constructor(private projectsService: ProjectsService) {
    super();
  }

  // Do not delete this comment
  // Append code in this place
  /**
   * @author: ThanhLD
   * @date: 2023-02-07 11:14:07
   * API deleteProject
   * Delete record
   * @param user: user authenticated
   * @param id: number
   * @returns boolean
   */
  @Mutation('deleteProject')
  async deleteProject(@GqlUser() user: UsersEntity, @Args('id') id: number) {
    const data = await this.projectsService.deleteProject(id, user);
    return this.response(data);
  }

  /**
   * @author: ThanhLD
   * @date: 2023-02-07 10:26:17
   * API addProject
   * Add new record
   * @param user: user authenticated
   * @param params: {url: string, comment:string}
   * @returns new inserted record
   */
  @Mutation('addProject')
  async addProject(@GqlUser() user: UsersEntity, @Args('params') params) {
    const data = await this.projectsService.addProject(user, params);
    return this.response(data);
  }

  /**
   * @author: ThanhLD
   * @date: 2023-02-07 08:51:29
   * API getProjects
   * Get list
   * @param user: user authenticated
   * @param pager: {limit: number, offset?: number, page?: number, isTakeAll?: boolean}
   * @returns  {data, paging}
   */
  @Query('getProjects')
  async getProjects(@GqlUser() user: UsersEntity, @Args('Pager') pager) {
    const data = await this.projectsService.getProjects(pager);
    return this.response(data);
  }
}
